version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "redis_server"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "darktheme-auth-fastapi-server"
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./logs:/var/log/app  # Map the local logs directory to /var/log/app in the container
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env  # Load environment variables from a .env file

volumes:
  redis_data:
